server:
  port: 8080

eureka:
  instance:
    hostname: localhost

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: service-a
          uri: lb://SERVICE-A
          predicates:
            - Path=/helloWorld
          filters:
            - AuthFilter

        - id: service-b
          uri: lb://SERVICE-B
          predicates:
            - Path=/helloEureka
          filters:
            - AuthFilter

        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**,/oauth2/**
#          filters:
#            - AuthFilter